"""empty message

Revision ID: 1f734b937e51
Revises: 
Create Date: 2022-12-06 19:18:40.087337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f734b937e51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'date')
    # ### end Alembic commands ###
