"""empty message

Revision ID: e2848856efa2
Revises: 1f734b937e51
Create Date: 2022-12-06 20:32:30.313501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2848856efa2'
down_revision = '1f734b937e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('domainDateUniqueConstraint', 'auction', ['domain', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('domainDateUniqueConstraint', 'auction', type_='unique')
    # ### end Alembic commands ###
